<?php

/**
 * @file
 * Conditional logic and data processing for uikit_blog.
 */

use Drupal\uikit\UIkit;

/**
 * Load uikit_blog's include files for theme processing.
 */
UIkit::loadIncludeFile('inc', 'uikit_blog', 'theme', 'preprocess', 'includes');
UIkit::loadIncludeFile('inc', 'uikit_blog', 'theme', 'process', 'includes');
UIkit::loadIncludeFile('inc', 'uikit_blog', 'theme', 'theme', 'includes');
UIkit::loadIncludeFile('inc', 'uikit_blog', 'theme', 'alter', 'includes');
