<img typeof="foaf:Image" src="/sites/uikit-drupal.com/files/images/getting-involved.png" width="1370" height="409" alt="Getting Involved">
<p>UIkit for Drupal is an open source Drupal project supported by people like you, those dedicated to offering the best open source projects without off-loading costs to the user. Lots of time, effort and love is put into the UIkit for Drupal project so we can provide the best Drupal experience as possible.</p>
<p class="uk-article-lead">Ways to get involved</p>
<div class="uk-width-1-1 uk-display-inline-block">
  <ul><li><a href="#test-report-bugs">Testing and reporting bugs</a></li>
    <li><a href="#write-submit-patches">Writing and submitting patches</a></li>
    <li><a href="#submit-feature-requests">Submitting feature requests</a></li>
    <li><a href="#submit-documentation-changes">Submitting/recommending documentation changes</a></li>
    <li class="uk-hidden"><a href="#donate">Donating to the project</a></li>
  </ul></div>
<div id="test-report-bugs">
  <h3>Testing and reporting bugs</h3>
  <p>By far the best way to getting involved is testing UIkit for Drupal and reporting bugs to the <a href="https://www.drupal.org/node/add/project-issue/uikit" target="_blank" class="drupal-api">issue queue</a> and selecting <em>Bug report</em> in the <strong>Category</strong> field. We keep a close eye on issues and try to respond as quickly as possible. Even if the issue ends up not being related to UIkit for Drupal, we do our best to get you back on track.</p>
</div>
<div id="write-submit-patches">
  <h3>Writing and submitting patches</h3>
  <p>If you're a developer or designer, you can get directly involved in the development of UIkit for Drupal by submitting patches to issues in the issue queue or a bug you find yourself. Information on how to create patches for Drupal with Git can be found <a href="https://www.drupal.org/node/707484" target="_blank" class="drupal-api">here</a>.<br><br>
    Then submit the patch by creating an issue or reply to an issue and use the <strong>add a new file</strong> field to upload the patch file you created. We'll apply the patch and test it in our development environment and allow the community to review the changes. If all is well the patch will be committed to the relevant development branch with a credit to your Drupal user account.</p>
</div>
<div id="submit-feature-requests">
  <h3>Submitting feature requests</h3>
  <p>We're always thinking of new ways to make UIkit for Drupal better, but most feature requests come from community members like yourself. We appreciate the contributions given to us by the community, so be sure to let us know what you think will make UIkit for Drupal better by submitting a new issue in the <a href="https://www.drupal.org/node/add/project-issue/uikit" target="_blank" class="drupal-api">issue queue</a> and selecting <em>Feature request</em> in the <strong>Category</strong> field.</p>
</div>
<div id="submit-documentation-changes">
  <h3>Submitting/recommending documentation changes</h3>
  <p>Changes to the documentation on this site is handled a little differently than submitting bugs, feature requests and support questions. Instead of using the issue queue, we have provided a form <a href="">here</a> for submitting changes or recommendations to the documentation. Simply fill out and submit the form and we'll be sure to get back to you as soon as possible. We'll work closely with you through email to get things going in the right direction.</p>
</div>