<?php

use Drupal\uikit\UIkit;

/**
 * Implements hook_menu().
 */
function uikit_examples_menu() {
  $items['tests'] = array(
    'title' => t('Tests'),
    'page callback' => '_uikit_examples_tests',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -49,
    'expanded' => TRUE,
    'options' => array(
      'attributes' => array(
        'docs-nolink' => '',
      ),
    ),
  );
  $items['tests/v2'] = array(
    'title' => t('v2 Tests'),
    'page callback' => '_uikit_examples_tests_v2',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -50,
  );
  $items['tests/v3'] = array(
    'title' => t('v3 Tests'),
    'page callback' => '_uikit_examples_tests_v3',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.module',
    'file path' => drupal_get_path('module', 'uikit_examples'),
    'module' => 'uikit_examples',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -49,
  );

  return $items;
}

function _uikit_examples_tests() {
  drupal_goto('tests/v3');
}

function _uikit_examples_tests_v2() {
  _uikit_examples_examples_js();
  $src = '/' . drupal_get_path('module', 'uikit_examples') . '/includes/uikit/uikit-v2/tests/overview.html';
  $output = '<iframe id="uikit-tests" src="' . $src . '" style="height: 1487px; width: 100%; box-shadow: 0 5px 15px rgba(0,0,0,0.1);"></iframe>';
  return $output;
}

function _uikit_examples_tests_v3() {
  _uikit_examples_examples_js();
  $src = '/' . drupal_get_path('module', 'uikit_examples') . '/includes/uikit/uikit-v3/tests/index.html';
  $output = '<iframe id="uikit-tests" src="' . $src . '" style="height: 4643px; width: 100%; box-shadow: 0 5px 15px rgba(0,0,0,0.1);"></iframe>';

  return $output;
}

function _uikit_examples_examples_js() {
  $js = drupal_get_path('module', 'uikit_examples') . '/uikit_examples.js';
  drupal_add_js($js, array(
    'type' => 'file',
    'group' => JS_THEME,
    'scope' => 'footer',
    'weight' => 1000,
  ));
}
