<?php

/**
 * Implements hook_menu().
 */
function uikit_examples_menu() {
  $items['examples'] = array(
    'title' => 'UIkit Examples',
    'page callback' => '_uikit_examples_tests_v3',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.pages.inc',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'weight' => -49,
  );
  // Tabs begin here.
  $items['examples/v3'] = array(
    'title' => 'UIkit v3 Examples',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['examples/v2'] = array(
    'title' => 'UIkit v2 Examples',
    'page callback' => '_uikit_examples_tests_v2',
    'access arguments' => array('access content'),
    'file' => 'uikit_examples.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function _uikit_examples_examples_js() {
  $js = drupal_get_path('module', 'uikit_examples') . '/uikit_examples.js';
  drupal_add_js($js, array(
    'type' => 'file',
    'group' => JS_THEME,
    'scope' => 'footer',
    'weight' => 1000,
  ));
}
